var config = {
    style:  'mapbox://styles/synngatech/cm2tit89i00ix01qi8cq205c3',
    accessToken: 'pk.eyJ1Ijoic3lubmdhdGVjaCIsImEiOiJjbTF4dGF1cTkwdnZ1MmtxMWRwNDgwazVpIn0.aoTqmmjvf-wJDx-0zbBq5A',
    showMarkers: false,
    markerColor: '#3FB1CE',
    inset: false,
    use3dTerrain: false,
    theme: 'light',
    introtitle: '2024 Fall Community Dynamics and Engagement \n Neighborhood Case Study \n Georgia Institute of Technology',
    title: 'Grey Ithaca Downtown',
    subtitle: "History of Ithaca Downtown \n and Problems.",
    author: "October 2024 \n SungHo Synn",
    byline: 'Introduction',
    para1: 'This research delves into the examination and analysis of Cooling Centers, vital welfare facilities catering to the needs of vulnerable elderly populations confronting extreme summer climate conditions in Seoul, South Korea. The primary objective of this study was to evaluate the effectiveness of Cooling Centers in each administrative district, with a focus on their capacities to meet the rising demand. By doing so, this research aims to contribute valuable insights to the provision of welfare services in appropriate locations.',
    para2: 'The analysis revealed that several administrative districts in Seoul struggled to secure Cooling Centers with capacities matching the elderly vulnerable population. Additionally, the availability of overnight accommodations in these facilities was generally limited across the city. These findings emphasize the urgent need for solutions to assist elderly vulnerable populations in coping with prolonged tropical heat in Seoul. Furthermore, the research highlights that Cooling Centers should consider other vulnerable groups in addition to the elderly in their services.',
    footer: 'Source: Bae, Min-Ki, Bo-Eun Kim, and Chae-Yeon Lee. 2020. “Analysis on the Spatial Relationship between the Residential Area of the Vulnerable Groups and the Hazardous Area during the Heat Wave.” Journal of Environmental Policy and Administration 28 (3): 243~80. \n Hyunmi, Kang, and Park Sohyun. 2007. “Characteristics of Walking Environment in Apartment Complexes on Gradient Sites.” Architecutre & Urban Research Information Center, November. \n Jenerette, G. Darrel, Sharon L. Harlan, William L. Stefanov, and Chris A. Martin. 2011. “Ecosystem Services and Urban Heat Riskscape Moderation: Water, Green Spaces, and Social Inequality in Phoenix, USA.” Ecological Applications: A Publication of the Ecological Society of America 21 (7): 2637~51. \n Jung, Sangyun, and Dong-Wook Sohn. 2019. “An Evaluation of Pedestrian Environments based on the Criteria of Universal Design Theory - A case study of old town area in Seoul -.” Journal of the architectural institute of Korea planning & design 35 (1): 117~25. \n Kim, Jin-Wook. 2008. “A Study on the Cooling Center Manual of Facility and Maintenance for Extreme Heat Disaster.” Journal of the Korean Society of Hazard Mitigation 8 (4): 17~22. \n Lee, Min. 2022. Establishing Guideline for Elderly Peoples Healthy Life. National Evidence-based Healthcare Collaborating Agency. \n Park, Seongwoo, Joo-Yeon Hwang, Hyoeun Kim, Youngju Lee, JongHee Kim, and Younjhin Ahn. 2023. “Results of the 2022 Heat-Related Illness Surveillance.” Public Health Weekly Report 16 (Issue: 9): Pages: 241-252. \n Son, Ho-Hee, and Eun-Jung Kim. 2013. “Analysis of Spatio-Temporal Parameters of Gait in Elderly by Various Walking Pathways Width.” The Journal of the Korea Contents Association 13 (10): 444~51. \n Song, Gowook. 2013. “Emergency Measures for Vulnerable Populations to Heatwaves.” Busan Development Institute, no. BDI Focus (June). \n Yoon, Yongseon, Sanggweon Lee, and Hwenghwan Ahn. 2016. “A long-term counterproposal of Heat wave damage measures for climate change.” Journal of disaster prevention v.18 no.5, pp.12-35. <br> Created using <a href="https://github.com/mapbox/storytelling" target="_blank">Mapbox Storytelling</a> template.',
    
    chapters: [
        {
            id: '1st-chapter',
            alignment: 'center',
            hidden: false,
            image: 'https://github.com/Synn-Arch/GreyIthaca/blob/main/images/ChaptersTitle1.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 13,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'tompkins', opacity: 0},
                {layer: 'newyork', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 0},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'tompkins', opacity: 1},
                {layer: 'newyork', opacity: 1},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},         
                {layer: 'accomorate', opacity: 0},        
                {layer: 'topfiveline', opacity: 0},  
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},  
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},           
            ],     
        },
        {
            id: '2nd-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Where is Ithaca?',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/coolingCenter.jpg?raw=true',
            description: 'The City of Ithaca, where downtown Ithaca is located, originated as a small commercial hub at the southern tip of Cayuga Lake in Upstate New York.',
            location: {
                center: [-79.4967, 42.43962],
                zoom: 6,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'tompkins', opacity: 1},
                {layer: 'newyork', opacity: 1},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'tompkins', opacity: 0},
                {layer: 'newyork', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],      
        },
        {
            id: '3rd-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Tompkins County',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/FacilityCategories.jpg?raw=true',
            description: '그중에서도 Tompkins County',
            location: {
                center: [-76.75602, 42.45068],
                zoom: 10,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'tompkins', opacity: 1},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 1},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],     
        },
        {
            id: '4th-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Downtown Ithaca',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/coolingCenter2.jpg?raw=true',
            description: 'Downtown은 그 중에서도 Ithaca의 중심지입니다.',
            location: {
                center: [-76.49942, 42.43908],
                zoom: 16.09,
                pitch: 60.31,
                bearing: -45.57
            },
            mapAnimation: 'flyTo',
            rotateAnimation: true,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "visible";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 1},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 1},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],     
        },
        {
            id: '5th-chapter',
            alignment: 'left',
            hidden: false,
            title: 'History of Ithaca ',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/coolingCenter2.jpg?raw=true',
            description: 'Downtown은 그 중에서도 Ithaca의 중심지입니다.',
            location: {
                center: [-76.49942, 42.43908],
                zoom: 16.09,
                pitch: 60.31,
                bearing: -45.57
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "visible";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 1},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 1},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],     
        },
        {
            id: '6th-chapter',
            alignment: 'left',
            hidden: false,
            title: 'Occupancy Rate',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/SleepingCoolingCenter.jpeg?raw=true',
            description: 'A total of 164 administrative districts (comprising 38% of the sample) failed to secure any Cooling Centers with lodging capabilities, while 354 administrative districts (constituting 83% of the sample) exhibited accommodation capacities that fell below 50% concerning the elderly population.',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "visible";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 1},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],        
        },
        { 
            id: 'focus1',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8.jpg?raw=true',
            description: 'Utilizing the findings derived from the analysis presented in Chapter Three, I identified the five administrative districts characterized by the lowest Ratio of Facility Capacity to Low-Income Elderly Population. These districts exhibit occupancy rates spanning from 11% to 20%, with the overnight stay occupancy rate falling within the range of 0% to 18%. These findings underscore the inadequacy of Cooling Centers capacity and quantity in addressing the requirements of the vulnerable elderly population.',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],        
        },
        {
            id: 'why?',
            alignment: 'center',
            hidden: false,
            title: 'By the way, why there are lack of Cooling Centers?',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201.jpg?raw=true',
            description: ' The majority of Cooling Centers are designated within Senior Community Centers, so excluding Senior Community Centers, the number of facilities used as Cooling Centers is very limited. ',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
                
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 1},
                {layer: 'expenditureforelder', opacity: 0},
            ],      
        },
        { 
            id: '1st reason',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8.jpg?raw=true',
            description: 'Since Cooling Centers in Seoul are temporary facilities designated within existing facilities, it is important to make good use of the existing infrastructure. But there is no guarantee that Senior Community Centers will be installed where vulnerable elderly populations reside in clusters. \n In the majority of the five designated target areas, when excluding Senior Community Centers, it becomes evident that there is an insufficient presence of significant Cooling Centers. This indicates the need to expand the category of facilities designated as Cooling Centers.',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 1},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],     
        },       
        {
            id: 'where?',
            alignment: 'center',
            hidden: false,
            title: 'We need more Cooling Center',
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/IdontknowCoolingCenter.jpg?raw=true',
            description: '“I dont know about a cooling center, I am just sitting here because it gets hot after lunch.”',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],      
        },
        { 
            id: 'elder',
            alignment: 'center',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/%EB%AC%B4%EC%A0%9C-2_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%202_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%202.png?raw=true',
            description: 'Primarily, in the scrutiny of the suitability of Cooling Center siting, a pivotal consideration revolves around determining the optimal pedestrian distance that elderly individuals can traverse under conditions of extreme heat. For this, statistical data derived from prior scholarly investigations is utilized(Son and Kim 2013).',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 1},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0.5},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],        
        },
        {
            id: '7thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%203.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],        
        },
        {
            id: '8thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%204.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],              
        },
        {
            id: '10thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%205.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],  
        },
        {
            id: '11thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%206.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],  
        },
        {
            id: '12thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%207.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],  
        },
        {
            id: '13thchapter',
            alignment: 'left',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/1_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8%208.jpg?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0,
              speed: .5, // make the flying slow
              curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "visible";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 1},
                {layer: 'walking', opacity: 0.5},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 1},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0.5},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 1},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0.2},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],  
        },
        {
            id: 'conclusion',
            alignment: 'center',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/s_%EB%8C%80%EC%A7%80%201%20%EC%82%AC%EB%B3%B8.png?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0.2},
                {layer: 'seoul-fill2', opacity: 0},    
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},              
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0.2},   
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},                
            ],  
        },
        {
            id: 'conclusion2',
            alignment: 'center',
            hidden: false,
            image: 'https://github.com/Synn-Arch/Seoul-is-too-hot/blob/main/images/%EB%AC%B4%EC%A0%9C-2_%EB%8C%80%EC%A7%80%201.png?raw=true',
            location: {
                center: [-76.4967, 42.43962],
                zoom: 20,
                pitch: 0,
                bearing: 0
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback:() => {
                document.getElementById("capacity_legend").style.visibility = "hidden";
                document.getElementById("ac_legend").style.visibility = "hidden";
                document.getElementById("accomo_legend").style.visibility = "hidden";
                document.getElementById("walking_legend").style.visibility = "hidden";
            },
            onChapterEnter: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 1},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0.2},    
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},            
            ],
            onChapterExit: [
                {layer: 'capacity', opacity: 0},
                {layer: 'status', opacity: 0},
                {layer: 'walking', opacity: 0},
                {layer: 'dongline', opacity: 0},
                {layer: 'seoul', opacity: 0},
                {layer: 'newcenter', opacity: 0},
                {layer: 'topfive', opacity: 0},
                {layer: 'newwalking', opacity: 0},
                {layer: 'acrate', opacity: 0},
                {layer: 'accomorate', opacity: 0},  
                {layer: 'topfiveline', opacity: 0},
                {layer: 'seoul-fill1', opacity: 0},
                {layer: 'seoul-fill2', opacity: 0},
                {layer: 'statustwo', opacity: 0},
                {layer: 'expenditureforelder', opacity: 0},
            ],              
        },

        
    ]
};
